package net.sf.taverna.t2.activities.jsonpath;

import net.sf.taverna.t2.visit.VisitKind;
import net.sf.taverna.t2.visit.Visitor;

/**
 * A <code>JsonPathActivityHealthCheck</code> is a kind of visit that determines
 * if the corresponding JsonPath activity in a workflow (normally an Activity)
 * will work during a workflow run.
 * 
 * @author Sergejs Aleksejevs
 */
public class JsonPathActivityHealthCheck extends VisitKind {

  // The following values indicate the type of results that can be associated
  // with a VisitReport generated by a health-checking visitor.

  public static final int CORRECTLY_CONFIGURED = 0;
  public static final int EMPTY_JSONPATH_EXPRESSION = 5;
  public static final int INVALID_JSONPATH_EXPRESSION = 10;
  public static final int GENERAL_CONFIG_PROBLEM = 15;
  
  public static final int NO_EXAMPLE_DOCUMENT = 20;
  
  @Override
  public Class<? extends Visitor> getVisitorClass() {
    return JsonPathActivityHealthChecker.class;
  }
  
  private static class Singleton {
    private static JsonPathActivityHealthCheck instance = new JsonPathActivityHealthCheck();
  }
  
  public static JsonPathActivityHealthCheck getInstance() {
    return Singleton.instance;
  }
}
